apiVersion: backstage.io/v1alpha1
kind: Component

metadata:
  name: 
  description: Service 

  annotations:
    github.com/project-slug: Backstage-IDP-PoC/
    backstage.io/techdocs-ref: dir:.
    jenkins.io/job-full-name: Backstage_PoC//main
    argocd/app-name: 
    backstage.io/kubernetes-id: 
    backstage.io/kubernetes-namespace: default
    sonarqube.org/project-key: 
    
spec:
  type: service
  owner: development
  lifecycle: experimental
